### Creating DB ###

DROP DATABASE IF EXISTS `NEDB`;
CREATE DATABASE `NEDB`;

### Creating Tables ###

CREATE TABLE `PERSONA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRES` VARCHAR(255),
	`APELLIDOS` VARCHAR(255),
	`GENERO` ENUM('M','F'),
	`DNI` INT UNIQUE,
	`TELEFONO` VARCHAR(255),
	`EMBARAZO` ENUM('S','N'),
	`JEFE_FAMILIA` ENUM('S','N'),
	`BONO` ENUM('S','N'),
	`PENSIONADO` ENUM('NT', 'AM', 'SS'),
	`GRADO_INSTRUCCION` ENUM('NT', 'MATERNAL', 'PREESCOLAR', 'PRIMARIA', 'SECUNDARIA', 'PREGRADO',
		'POSTGRADO', 'MAESTRIA', 'DOCTORADO'),
	`CARGO_LABORAL` ENUM('NT', 'PRIVADO', 'PUBLICO', 'OTRO'),
	`VOTO` ENUM('D','B','O'),
	`FECHA_NAC` DATE,
	`PESO` FLOAT,
	`ESTATURA` FLOAT,
	`SERIAL_CARNET` VARCHAR(255),
	`CODIGO_CARNET` VARCHAR(255),
	`ID_FAMILIA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `PROGRAMASOCIAL`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `REL_PERSONAPROGRAMA`(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_PROGRAMA` INT,
	`ID_PERSONA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `DISCAPACIDAD`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`ID_TIPO` INT,
	`ID_PERSONA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `TIPODISCAPACIDAD`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`TIPO` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `BOMBONA`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`ID_FAMILIA` INT,
	`ID_TIPO` INT(2),
	`ID_MARCA` INT(2),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `TIPOBOMBONA`(
	`ID`INT(2) NOT NULL AUTO_INCREMENT,
	`TIPO` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `MARCABOMBONA`(
	`ID`INT(2) NOT NULL AUTO_INCREMENT,
	`MARCA` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `FAMILIA`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`ID_APARTAMENTO` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `APARTAMENTO`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`NUMERO_APARTAMENTO` INT(2) UNSIGNED ZEROFILL,
	`ANEXO` ENUM('S','N'),
	`ID_BLOQUE` INT(1),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `BLOQUE`(
	`ID`INT(1) NOT NULL AUTO_INCREMENT,
	`NUMERO_BLOQUE` INT(2) UNSIGNED ZEROFILL,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `BENEFICIO`(
	`ID`INT NOT NULL AUTO_INCREMENT,
	`FECHA_ENTREGA` DATE,
	`ID_FAMILIA` INT,
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

CREATE TABLE `USUARIO`(
	`ID` INT(1) NOT NULL AUTO_INCREMENT,
	`USUARIO` VARCHAR(255) UNIQUE,
	`NOMBRE` VARCHAR(255),
	`APELLIDO` VARCHAR(255),
	`CLAVE` VARCHAR(255),
	PRIMARY KEY (`ID`)
)ENGINE=InnoDB;

### Creating foreign keys ###

ALTER TABLE `PERSONA`
	ADD FOREIGN KEY (`ID_FAMILIA`) REFERENCES `FAMILIA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `REL_PERSONAPROGRAMA`
	ADD FOREIGN KEY (`ID_PROGRAMA`) REFERENCES `PROGRAMASOCIAL` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `DISCAPACIDAD`
	ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPODISCAPACIDAD` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BOMBONA`
	ADD FOREIGN KEY (`ID_FAMILIA`) REFERENCES `FAMILIA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPOBOMBONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
	ADD FOREIGN KEY (`ID_MARCA`) REFERENCES `MARCABOMBONA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `FAMILIA`
	ADD FOREIGN KEY (`ID_APARTAMENTO`) REFERENCES `APARTAMENTO` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `APARTAMENTO`
	ADD FOREIGN KEY (`ID_BLOQUE`) REFERENCES `BLOQUE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `BENEFICIO`
	ADD FOREIGN KEY (`ID_FAMILIA`) REFERENCES `FAMILIA` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

### Adding default values ###

INSERT INTO `USUARIO` (`USUARIO`,`CLAVE`) VALUES
	('admin','1234');

INSERT INTO `BLOQUE` (`NUMERO_BLOQUE`) VALUES
	(1),(2),(3),(4),(5),(6),(7),(8);

INSERT INTO `APARTAMENTO` (`NUMERO_APARTAMENTO`,`ID_BLOQUE`,`ANEXO`) VALUES
	(1,1,'N'),(2,1,'N'),(3,1,'N'),(4,1,'N'),(5,1,'N'),(6,1,'N'),(7,1,'N'),(8,1,'N'),(9,1,'N'),(10,1,'N'),
	(11,1,'N'),(12,1,'N'),(13,1,'N'),(14,1,'N'),(15,1,'N'),(16,1,'N'),(17,1,'N'),(18,1,'N'),(19,1,'N'),(20,1,'N'),
	(21,1,'N'),(22,1,'N'),(23,1,'N'),(24,1,'N'),(25,1,'N'),(26,1,'N'),(27,1,'N'),(28,1,'N'),
	(1,2,'N'),(2,2,'N'),(3,2,'N'),(4,2,'N'),(5,2,'N'),(6,2,'N'),(7,2,'N'),(8,2,'N'),(9,2,'N'),(10,2,'N'),
	(11,2,'N'),(12,2,'N'),(13,2,'N'),(14,2,'N'),(15,2,'N'),(16,2,'N'),(17,2,'N'),(18,2,'N'),(19,2,'N'),(20,2,'N'),
	(21,2,'N'),(22,2,'N'),(23,2,'N'),(24,2,'N'),(25,2,'N'),(26,2,'N'),(27,2,'N'),(28,2,'N'),
	(1,3,'N'),(2,3,'N'),(3,3,'N'),(4,3,'N'),(5,3,'N'),(6,3,'N'),(7,3,'N'),(8,3,'N'),(9,3,'N'),(10,3,'N'),
	(11,3,'N'),(12,3,'N'),(13,3,'N'),(14,3,'N'),(15,3,'N'),(16,3,'N'),(17,3,'N'),(18,3,'N'),(19,3,'N'),(20,3,'N'),
	(21,3,'N'),(22,3,'N'),(23,3,'N'),(24,3,'N'),(25,3,'N'),(26,3,'N'),(27,3,'N'),(28,3,'N'),
	(1,4,'N'),(2,4,'N'),(3,4,'N'),(4,4,'N'),(5,4,'N'),(6,4,'N'),(7,4,'N'),(8,4,'N'),(9,4,'N'),(10,4,'N'),
	(11,4,'N'),(12,4,'N'),(13,4,'N'),(14,4,'N'),(15,4,'N'),(16,4,'N'),(17,4,'N'),(18,4,'N'),(19,4,'N'),(20,4,'N'),
	(21,4,'N'),(22,4,'N'),(23,4,'N'),(24,4,'N'),(25,4,'N'),(26,4,'N'),(27,4,'N'),(28,4,'N'),
	(1,5,'N'),(2,5,'N'),(3,5,'N'),(4,5,'N'),(5,5,'N'),(6,5,'N'),(7,5,'N'),(8,5,'N'),(9,5,'N'),(10,5,'N'),
	(11,5,'N'),(12,5,'N'),(13,5,'N'),(14,5,'N'),(15,5,'N'),(16,5,'N'),(17,5,'N'),(18,5,'N'),(19,5,'N'),(20,5,'N'),
	(21,5,'N'),(22,5,'N'),(23,5,'N'),(24,5,'N'),(25,5,'N'),(26,5,'N'),(27,5,'N'),(28,5,'N'),
	(1,6,'N'),(2,6,'N'),(3,6,'N'),(4,6,'N'),(5,6,'N'),(6,6,'N'),(7,6,'N'),(8,6,'N'),(9,6,'N'),(10,6,'N'),
	(11,6,'N'),(12,6,'N'),(13,6,'N'),(14,6,'N'),(15,6,'N'),(16,6,'N'),(17,6,'N'),(18,6,'N'),(19,6,'N'),(20,6,'N'),
	(21,6,'N'),(22,6,'N'),(23,6,'N'),(24,6,'N'),(25,6,'N'),(26,6,'N'),(27,6,'N'),(28,6,'N'),
	(1,7,'N'),(2,7,'N'),(3,7,'N'),(4,7,'N'),(5,7,'N'),(6,7,'N'),(7,7,'N'),(8,7,'N'),(9,7,'N'),(10,7,'N'),
	(11,7,'N'),(12,7,'N'),(13,7,'N'),(14,7,'N'),(15,7,'N'),(16,7,'N'),(17,7,'N'),(18,7,'N'),(19,7,'N'),(20,7,'N'),
	(21,7,'N'),(22,7,'N'),(23,7,'N'),(24,7,'N'),(25,7,'N'),(26,7,'N'),(27,7,'N'),(28,7,'N'),
	(1,8,'N'),(2,8,'N'),(3,8,'N'),(4,8,'N'),(5,8,'N'),(6,8,'N'),(7,8,'N'),(8,8,'N'),(9,8,'N'),(10,8,'N'),
	(11,8,'N'),(12,8,'N'),(13,8,'N'),(14,8,'N'),(15,8,'N'),(16,8,'N'),(17,8,'N'),(18,8,'N'),(19,8,'N'),(20,8,'N'),
	(21,8,'N'),(22,8,'N'),(23,8,'N'),(24,8,'N'),(25,8,'N'),(26,8,'N'),(27,8,'N'),(28,8,'N');
